services:
  - type: web
    name: ai-customer-service-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: REACT_APP_API_BASE_URL
        value: https://transforming-after-sales-support-backend.onrender.com
      - key: REACT_APP_API_URL
        value: https://transforming-after-sales-support-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://transforming-after-sales-support-backend.onrender.com
