services:
  - type: web
    name: ai-customer-service-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
      - key: REACT_APP_API_BASE_URL
        value: https://your-backend-url.onrender.com
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://your-backend-url.onrender.com
